# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tor Inge Jøssang - blog
email: tor.jossang@gmail.com
description: >
  - Journalist
logo: "/assets/images/logo.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.jossang.eu" # the base hostname & protocol for your site
paginate: 5 # The number of posts to show per page on your homepage

name: 'Tor Inge Jøssang'
bio: >
  Journalist ved Jørpelandkontoret til Stavanger Aftenblad
author_image: "/assets/images/author.jpg"
twitter_username: torjossang
github_username:  toro68

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate